### ISSUE TITLE
We’ll adjust ETA calculations based on real-time weather data, accounting for delays due to conditions like rain or fog. The UI will notify users of any changes, and tests will confirm accuracy across various weather scenarios.

### ISSUE THREAD

**Issue by furyhotspot** [CMPSC3943FA24/WeatherRoute#23]

**Comment by ankbas** [comment]
Update: Task is complete. The ETA calculations have been successfully adjusted based on real-time weather data, including delays due to conditions like rain or fog. The UI now notifies users of any changes, and tests have confirmed the accuracy of the calculations across various weather scenarios.
